### ISSUE TITLE
Broken extension icon menu on Vivaldi

### ISSUE THREAD

**Issue by defder-su** [gildas-lormeau/SingleFile#1059]
**Describe the bug**
The SingleFile extension icon menu doesn't contain some items.

**To Reproduce**
1. Install [Vivaldi 32-bit](https://vivaldi.com/download/).
2. Install [SingleFile](https://chrome.google.com/webstore/detail/singlefile/mpiodijhokgodhhofbcjdecpffjipkle/).
3. Tap on the SingleFile extension icon.

**Expected behavior**
Full menu including "Auto-save" submenu should be displayed.

**Screenshots**
<img width="205" alt="MenuOnVivaldi" src="https://user-images.githubusercontent.com/85085602/203541382-7a1db192-bfeb-4057-9969-816d0bb77985.png">

**Environment**
 - OS: Windows 10 64-bit
 - Browser: Vivaldi 5.5.2805.44 32-bit

**Additional context**
That's also reproducible in SingleFileZ.

**Comment by gildas-lormeau** [comment]
It should be fixed in the versions I published.

**Comment by defder-su** [comment]
Still reproducible with SingleFileZ 1.3.40 (presented today on the store).

**Comment by gildas-lormeau** [comment]
I cannot reproduce the issue. I did the test with Vivaldi 5.6.28005.48 and SingleFile 1.21.31. The "auto-save" entry is present in the menu.

**Comment by defder-su** [comment]
Reproduced on SingleFileZ 1.3.43.

**Comment by defder-su** [comment]
Unfortunately, I don't have technical possibility to reopen this issue.

**Comment by gildas-lormeau** [comment]
Did you change the user-agent of your browser?

**Comment by defder-su** [comment]
I didn't change the user-agent.

Could you please provide a link to commit which intended to fix it?

**Comment by gildas-lormeau** [comment]
It should have been fixed in SingleFile 23 days ago, see https://github.com/gildas-lormeau/SingleFile/commit/60a3eabfc217eb6a44e2cd54923df26654d9787c.
SingleFileZ does not include this kind of code. Indeed, I did not add code in SingleFileZ in order to remove entries in the menu because I did not port it on Safari.

**Comment by defder-su** [comment]
`User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36 Vivaldi/5.6.2867.36`

**Comment by gildas-lormeau** [comment]
Just to be sure, do you confirm that your bug is the fact the "Auto-save" entry does not appear in the context menu of SingleFile *$and SingleFileZ**?

**Comment by defder-su** [comment]
I were not tested previous versions.

**Comment by gildas-lormeau** [comment]
So, I was wrong, I applied the same changes in SingleFileZ actually. However, that still does not explain the cause of the issue. Do you see the "Auto-save" section in the options page?

**Comment by defder-su** [comment]
> So, I was wrong, I applied the same changes in SingleFileZ actually. However, that still does not explain the cause of the issue. Do you see the "Auto-save" section in the options page?

Yes.

**Comment by defder-su** [comment]
Seeing [screenshot](https://user-images.githubusercontent.com/85085602/203541382-7a1db192-bfeb-4057-9969-816d0bb77985.png), it looks like an issue on creating menu items with submenus.

**Comment by gildas-lormeau** [comment]
Ok, we are not talking about the same menu... I was talking about the context menu on the page actually, it's my fault. I confirm I can reproduce the issue. It looks like it's a bug in Vivaldi since Chrome does not suffer from this issue.

**Comment by gildas-lormeau** [comment]
I did a test with the version 1.21.23 of SingleFile and I see the same bug. This confirms it's a bug in Vivaldi.

**Comment by defder-su** [comment]
The context menu on the page works.

On Vivaldi, [IPFS Companion](https://github.com/ipfs/ipfs-companion) shows similar menu group when clicked on the icon:
<img width="196" alt="Снимок экрана 2022-12-08 в 14 32 25" src="https://user-images.githubusercontent.com/85085602/206447165-a625e896-a86f-40c4-8b55-2af3e4bb5090.png">

**Comment by defder-su** [comment]
> The context menu on the page works.

It allows me to use the auto-save feature on Vivaldi, in fact.
