### ISSUE TITLE
Provide support for an option to not auto-close a tab after cancelling a web page save

### ISSUE THREAD

**Issue by touwys** [gildas-lormeau/SingleFile#1490]
The dialogue for saving a web page with SingleFile, presents the user with the option to either save, or to cancel, saving the page.
  
It follows that if the user opts to _cancel_, the browser tab for that web page gets closed as soon as the save dialogue closes — that is, if the SingleFile configuration calls for it — as per `Options > User interface > auto-close the tab after the page is saved  > enabled`. I expected the tab _not_ to get closed, because the web page save was cancelled. Therefore, no need to auto-close the tab. 

If appropriate, could you please provide support for an option to not have the tab closed whenever a page is not saved? Example: 

**[Screenshot](https://github.com/gildas-lormeau/SingleFile/assets/65730626/4f3ee24b-eaea-4129-a4a8-2155f6223e0c)**

Thank you, and thank you very much too, for his splendid add-on.

**Comment by gildas-lormeau** [comment]
I was able to reproduce the issue. In fact, I did nit think about this case. I'll have to take a closer look, but it should be possible to fix this problem.

**Comment by gildas-lormeau** [comment]
I fixed this bug. The fix will be available in the next version.

**Comment by touwys** [comment]
> I fixed this bug. The fix will be available in the next version.

Thank you very much. Looking forward to the release of the new version.

**Comment by touwys** [comment]
Issue persists in SingleFile v1.22.54 (last updated 25 July 2024). 

Browser: Firefox v115.13.0esr
OS: Windows 7 x64 SP1

**Comment by gildas-lormeau** [comment]
I'm sorry, I confirm the issue is still reproducible in Firefox. It's fixed in Chrome though.

**Comment by gildas-lormeau** [comment]
I took a closer look at the issue in Firefox and fixed it. It should work as expected in the next version.
