### ISSUE TITLE
Saving a page from `messenger.com` and loading it in Firefox causes that tab to freeze, yet loading the original URI doesn't.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [gildas-lormeau/SingleFile#1497]
#### **Describe the bug**

Saving a page from https://www.messenger.com/ and loading it in Firefox causes that tab to freeze momentarily, yet loading the original URI doesn't.

#### **To Reproduce**

1.	I saved https://www.messenger.com/t/103856172576169 with the default `about:addons` configuration, except that all resources are enabled (else the original page wouldn't have been saved in its original form).
1.	I invoked the page (`file:///home/RokeJulianLockhart/Downloads/Messenger (11_07_2024 16_58_10).html`, available in https://github.com/user-attachments/files/16183112/Messenger.11_07_2024.16_58_10.zip) in Firefox.

#### **Expected behavior**

If the original site doesn't slow Firefox to anything near the amount that the saved page does, the saved page shouldn't either.

#### **Screenshots**

> ![Screenshot_20240711_211952](https://github.com/gildas-lormeau/SingleFile/assets/42837531/497c4d32-445d-4686-a9dd-6ddedff7fd1c)

#### **Environment**

 - **OS**: https://download.fedoraproject.org/pub/fedora/linux/releases/40/Spins/x86_64/iso/Fedora-KDE-Live-x86_64-40-1.14.iso  
 - **Browser**: https://packages.fedoraproject.org/pkgs/firefox/firefox/fedora-40-updates.html 
 - **Version**: https://kojipkgs.fedoraproject.org//packages/firefox/128.0/1.fc40/x86_64/firefox-128.0-1.fc40.x86_64.rpm from https://koji.fedoraproject.org/koji/rpminfo?rpmID=39112564 

#### **Additional context**

This is probably a performance bug in Firefox, but I'm going to nominally report it through here to ensure that it's not in some capacity a fault of this extension, even if, evidently, Firefox shouldn't ever not be able to cope with a mere HTML file. I can probably provide a performance report and/or flamegraph, if of use.

**Comment by gildas-lormeau** [comment]
Thank you for the detailed report. I confirm the problem you described when I open the saved page. The problem can be reproduced in Chome and Safari as well.
I see that scripts are included in the page and it looks like that JavaScript is the cause of the issue (infinite loop). SingleFile cannot really save scripts reliably. It only works for simple pages where scripts are directly included in the HTML markup. Could you try to save the page again with scripts blocked in the Network section of the options page?

**Comment by RokeJulianLockhart** [comment]
> https://github.com/gildas-lormeau/SingleFile/issues/1497#issuecomment-2223900918

@gildas-lormeau, scripts do appear to generally be what causes it, but I must admit, on my end, it's inconsistent - either file (that with and without scripts) can sometimes take a good moment to load, although the one with the script is always slower to respond when it does render.

**Comment by gildas-lormeau** [comment]
@RokeJulianLockhart  Thank you for your feedback. If possible, feel free to attach a file that would take too long to load even if the scripts are not included. I can take a look and maybe identify a bug in SingleFile.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/gildas-lormeau/SingleFile/issues/1497#issuecomment-2226428998

@gildas-lormeau, https://github.com/user-attachments/files/16202430/Messenger.13_07_2024.15_08_07.zip is a script-less version of my personal chat on Messenger. *Sometimes*, upon opening it for the first time, I have to close the tab and re-open it, but I think that's an issue with Firefox or my extensions, actually.

**Comment by gildas-lormeau** [comment]
I think the problem may be linked to your Firefox installation. I've tested the opening and reading of the page you've attached, and everything's fine on my end.

**Comment by gildas-lormeau** [comment]
I'm closing the issue. Feel free to comment if needed though :)

**Comment by RokeJulianLockhart** [comment]
@gildas-lormeau, as in, https://github.com/gildas-lormeau/SingleFile/issues/1497#issuecomment-2223900918 has been fixed?

**Comment by gildas-lormeau** [comment]
No, the bug is still present if scripts are included in the saved page. Generally speaking, this is "simply" due to the fact that scripts have not been designed for offline reading, unfortunately. I would recommend you to save scripts only if needed.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/gildas-lormeau/SingleFile/issues/1497#issuecomment-2229531719

Understandable, @gildas-lormeau. Maybe best closed as "Unplanned", then. At least, rather than "Completed".

**Comment by gildas-lormeau** [comment]
Thank you for the suggestion @RokeJulianLockhart, I've added some existing tags. As far as I know I cannot close the issue as unplanned in GitHub.

**Comment by RokeJulianLockhart** [comment]
@gildas-lormeau, perhaps you're affected by https://community.exalate.com/questions/42836801/answers/42836803. Apologies. I wasn't aware it wasn't available in some instances.

**Comment by gildas-lormeau** [comment]
Thank you, I was not aware of the existence of the dropdown menu included in the button. The issue is now closed as unplanned ;)
