### ISSUE TITLE
include-infobar option causes error

### ISSUE THREAD

**Issue by rsgranne** [gildas-lormeau/SingleFile#489]
**Describe the bug**
When I do _not_ use `--include-infobar=true` on the CLI, single-file works correctly; when I _do_ include it, no matter where I include it, I get an error that starts with `Stack: Error: Evaluation failed: TypeError: Cannot read property 'replace' of undefined`.

**To Reproduce**
1. In the terminal, enter the following:

`cd /Users/scott/Desktop && /Users/scott/node_modules/single-file/cli/single-file --filename-template "{page-title} - {date-iso}.html" --browser-executable-path /Applications/Brave\ Browser.app/Contents/MacOS/Brave\ Browser https://askubuntu.com/questions/76808/how-do-i-use-variables-in-a-sed-command`

2. This correctly downloads the webpage & creates the html file on my Desktop.
3. However, if I include `--include-infobar=true` in the command, it gives an error & the webpage is *not* saved on my Desktop.

~~~ shell
cd /Users/scott/Desktop && /Users/scott/node_modules/single-file/cli/single-file  --filename-template "{page-title} - {date-iso}.html" --include-infobar=true --browser-executable-path /Applications/Brave\ Browser.app/Contents/MacOS/Brave\ Browser --include-infobar=true https://askubuntu.com/questions/76808/how-do-i-use-variables-in-a-sed-command

URL: https://askubuntu.com/questions/76808/how-do-i-use-variables-in-a-sed-command
Stack: Error: Evaluation failed: TypeError: Cannot read property 'replace' of undefined
    at Object.includeScript (<anonymous>:8194:35)
    at __puppeteer_evaluation_script__:4:48
    at ExecutionContext._evaluateInternal (/Users/scott/node_modules/puppeteer-core/lib/ExecutionContext.js:102:19)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async ExecutionContext.evaluate (/Users/scott/node_modules/puppeteer-core/lib/ExecutionContext.js:33:16)
    at async getPageData (/Users/scott/node_modules/single-file/cli/back-ends/puppeteer.js:120:10)
    at async Object.exports.getPageData (/Users/scott/node_modules/single-file/cli/back-ends/puppeteer.js:44:10)
    at async capturePage (/Users/scott/node_modules/single-file/cli/single-file-cli-api.js:197:20)
    at async runNextTask (/Users/scott/node_modules/single-file/cli/single-file-cli-api.js:124:20)
    at async Promise.all (index 0)
    at async capture (/Users/scott/node_modules/single-file/cli/single-file-cli-api.js:75:2)
    at async run (/Users/scott/node_modules/single-file/cli/single-file:47:2)
  -- ASYNC --
    at ExecutionContext.<anonymous> (/Users/scott/node_modules/puppeteer-core/lib/helper.js:94:19)
    at DOMWorld.evaluate (/Users/scott/node_modules/puppeteer-core/lib/DOMWorld.js:89:24)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
  -- ASYNC --
    at Frame.<anonymous> (/Users/scott/node_modules/puppeteer-core/lib/helper.js:94:19)
    at Page.evaluate (/Users/scott/node_modules/puppeteer-core/lib/Page.js:612:14)
    at Page.<anonymous> (/Users/scott/node_modules/puppeteer-core/lib/helper.js:95:27)
    at getPageData (/Users/scott/node_modules/single-file/cli/back-ends/puppeteer.js:120:21)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Object.exports.getPageData (/Users/scott/node_modules/single-file/cli/back-ends/puppeteer.js:44:10)
    at async capturePage (/Users/scott/node_modules/single-file/cli/single-file-cli-api.js:197:20)
    at async runNextTask (/Users/scott/node_modules/single-file/cli/single-file-cli-api.js:124:20)
    at async Promise.all (index 0)
    at async capture (/Users/scott/node_modules/single-file/cli/single-file-cli-api.js:75:2)
  -- ASYNC --
    at Page.<anonymous> (/Users/scott/node_modules/puppeteer-core/lib/helper.js:94:19)
    at getPageData (/Users/scott/node_modules/single-file/cli/back-ends/puppeteer.js:120:21)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Object.exports.getPageData (/Users/scott/node_modules/single-file/cli/back-ends/puppeteer.js:44:10)
    at async capturePage (/Users/scott/node_modules/single-file/cli/single-file-cli-api.js:197:20)
    at async runNextTask (/Users/scott/node_modules/single-file/cli/single-file-cli-api.js:124:20)
    at async Promise.all (index 0)
    at async capture (/Users/scott/node_modules/single-file/cli/single-file-cli-api.js:75:2)
    at async run (/Users/scott/node_modules/single-file/cli/single-file:47:2)
~~~

**Expected behavior**
I expect the webpage to download without the error.

**Environment**
 - OS: macOS 10.15.6
 - Browser: Brave
 - Version: 1.13.86 Chromium: 85.0.4183.102 (Official Build) (64-bit)

**Additional Context**
This error occurs for every webpage I try with the command.

**Comment by gildas-lormeau** [comment]
Thank you for having reported this issue. It should be fixed now.

**Comment by alirezafarnoosh** [comment]
I think its not fixed btw.
```

'D:\work\single-file-cli-master>node.exe single-file https://www.wikipedia.org wikipedia.html --browser-executable-path="C:\Program Files (x86)\Google\Chrome\Application\chrome.exe" --include-infobar=true'


Evaluation failed: ReferenceError: infobar is not defined
    at pptr://__puppeteer_evaluation_script__:4:5 URL: https://www.wikipedia.org
Stack: Error: Evaluation failed: ReferenceError: infobar is not defined
    at pptr://__puppeteer_evaluation_script__:4:5
    at ExecutionContext._ExecutionContext_evaluate (D:\work\node_modules\puppeteer-core\lib\cjs\puppeteer\common\ExecutionContext.js:271:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ExecutionContext.evaluate (D:\work\node_modules\puppeteer-core\lib\cjs\puppeteer\common\ExecutionContext.js:118:16)
    at async getPageData (D:\work\single-file-cli-master\back-ends\puppeteer.js:139:10)
    at async exports.getPageData (D:\work\single-file-cli-master\back-ends\puppeteer.js:51:10)
    at async capturePage (D:\work\single-file-cli-master\single-file-cli-api.js:253:20)
    at async runNextTask (D:\work\single-file-cli-master\single-file-cli-api.js:174:20)
    at async Promise.all (index 0)
    at async capture (D:\work\single-file-cli-master\single-file-cli-api.js:125:2)
    at async run (D:\work\single-file-cli-master\single-file:54:2
```

Expected behavior
I expect the webpage to download without the error.

Environment

OS: windows 11 21H2
Browser: Chrome
Version: 104.0.5112.102 (Official Build) (64-bit)
Additional Context
This error occurs in wsl linux - windows - nodejs ver 13 , 16 ,18
