### ISSUE TITLE
SingleFile slows down Overleaf, an online Latex editor

### ISSUE THREAD

**Issue by wydwww** [gildas-lormeau/SingleFile#755]
**Describe the bug**
After installing SingleFile, editing a Latex project on https://www.overleaf.com/ becomes lagging and less responsive. Firefox gives the following warning:

> "SingleFile" is slowing down Firefox. To speed up your browser, stop that extension. Learn more at https://support.mozilla.org/en-US/kb/warning-unresponsive-script#w_other-causes

After disabling SingleFile, the issue disappears. The Overleaf lagging issue will re-appear if re-enabling SingleFile.

Throughout the whole process, the SingleFile button was never clicked.

**To Reproduce**
1. Working on an overleaf project for several minutes
2. The website becomes lagging
3. The Firefox warning will appear

**Expected behavior**
I suppose if SingleFile was not activated, it would not affect a website. Not sure if this is a site-specific issue.

**Environment**
 - OS: Windows 10 (8GB memory)
 - Browser: Firefox
 - Version: 91.0

**Comment by gildas-lormeau** [comment]
I did some tests here is what I noticed:
- A script on overleaf.com calls the [`FontFace`](https://developer.mozilla.org/docs/Web/API/FontFace) constructor to load fonts
- SingleFile intercepts these calls in order to store the family name and the URL of these fonts in a temporary structure, that's why the message "SingleFile is hooking the FontFace constructor to get font URLs." is displayed in the console.

I also see that:
- Each time the document is saved, the script on overleaf.com calls again the `FontFace` constructor even if no fonts have been added or removed.
- This script gives a different family name to these fonts each time it executes even if they did not change.

Due to the fact that the family name of fonts changes every time, the temporary structure keeps growing. I guess this is the cause of the issue you're describing.

I will try to see what I can do on my side to optimize my code to fight against these incessant calls to the `FontFace` constructor but it will not be trivial. Note that unfortunately, it's technically impossible for me to add an option to disable this feature in SingleFile because the SingleFile code has to be executed synchronously before the page is loaded. However, it's impossible to get the options at that moment because they are retrieved asynchronously.

**Comment by gildas-lormeau** [comment]
By debugging more carefully the code, I also noticed that the script on overleaf.com calls [`document.fonts.delete`](https://developer.mozilla.org/en-US/docs/Web/API/Document/fonts) to delete the obsolete fonts when saving the document. I added some code in SingleFile to handle this and make sure there won't be any memory leak. Hopefully, this should fix your issue as well. The fix will be available in the version 1.18.98.

**Comment by wydwww** [comment]
@gildas-lormeau Thank you so much for such a quick fix.

**Comment by gildas-lormeau** [comment]
You're welcome. I just uploaded the new version on the store. You'll be able to test it once reviewed by Mozilla and published on the store. Feel free to reopen the issue if you don't see any improvement. I'm not 100% sure the bug I fixed will fix your issue.

**Comment by wydwww** [comment]
Hi @gildas-lormeau, I updated to the latest 1.18.99 version, and the lagging issue has been fixed for most of the time, but still exists after compiling PDF.

After clicking the Recompile button or `ctrl + s`, scrolling and clicking on the page will temporarily become laggy for ~10s, then return back to normal. Can fix and reproduce by turning SingleFile off/on.

Can you please take another look? Thanks.

**Comment by gildas-lormeau** [comment]
@wydwww The version 1.19.10 of SingleFile (publish in progress) should fix the issue.
