### ISSUE TITLE
Problems with two websites (failure to save pages, or to save embedded images)

### ISSUE THREAD

**Issue by abolibibelot1980** [gildas-lormeau/SingleFile#843]
1) SingleFile always fails to save pages from Vavideo.de, getting stuck at step 1.
Example :
https://www.vavideo.de/inhalt?id=2793445
Save Page WE works fine on this website.

2) SingleFile fails to save embedded images from Indexxx.com, this even if making sure that all images have been loaded in the browser before proceeding to save the page.
Example (kinda NSFW) :
https://www.indexxx.com/m/mia-sollis
When reloading the saved page into Firefox, I can see that all embedded pictures are blank.
(It should be noted that downloading the actual cover pictures from that website is tricky, I made a curl script to batch download those from that page, for it to work each command had to include a time-limited "cookie" element obtained from the browser's network analyser.)
Save Page WE issues a warning saying that (for instance) “217 of 339 resources could not be loaded” (and the resulting file likewise does not include the pictures even though it's about twice as large as the one produced by SingleFile), so it doesn't work well either but at least it lets the user know it right away that something is wrong. Generally speaking, even for issues that can't be fixed, displaying that kind of warning would be welcome.

**Environment**
 - OS: Windows 7 Pro
 - Browser: Firefox 95 64 bits

**Comment by gildas-lormeau** [comment]
Thank, I fixed the first issue, the fix will be available in the next version. Meanwhile, you can circumvent it by disabling "Stylesheets > compress CSS content" (it's disabled by default). I'm not 100% sure this was your bug though since I don't know your settings.

I have mixed feelings about the second issue. The problem is false negatives. I have already tested the extension you mention and I personally find the warning window annoying. Most of the time the page is intact while the popup indicates that some resources have not been saved. I don't want to provide this kind of user experience.

**Comment by gildas-lormeau** [comment]
This issue is fixed actually.

**Comment by rauzaen** [comment]
> This issue is fixed actually.

Did the second issue ever get fixed? I can still reproduce the issue on the indexxx website on v1.22.78
Opera Browser (v95.0.4635.84) on W8.1
